# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build
      run: |
        ./gradlew shadowJar
    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        name: EmmyLuaLs
        path: ${{ github.workspace }}/EmmyLua-LS/build/libs
  release:
    name: Upload Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: [ubuntu-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
          id: create_release
          uses: actions/create-release@master
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body: ${{ github.ref }}
            draft: false
            prerelease: true

      - name: Download
        uses: actions/download-artifact@v2

      - name: Upload Runtime
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: EmmyLuaLs/EmmyLua-LS-all.jar
          asset_name: EmmyLua-LS-all.jar
          asset_content_type: application/jar
